# Sckikit Learn

Dividir el conjunto de datos disponible, en datos para pruebas y datos para test

In [2]:
import pandas as pd
import numpy as np
from  sklearn.model_selection import train_test_split

In [3]:
datos = np.random.randint(0,100,(100,4))

In [4]:
datos

array([[82, 13, 42, 78],
       [45, 96, 98, 95],
       [90, 35, 75, 80],
       [70,  4,  2, 82],
       [34, 22, 53, 99],
       [26, 61, 98, 23],
       [90, 67, 85, 40],
       [90, 43, 39, 13],
       [88, 97,  1, 58],
       [73, 87, 57, 39],
       [95, 69, 32,  1],
       [52, 24,  3,  6],
       [ 2, 34, 67, 47],
       [73, 53,  5, 67],
       [ 3, 12, 94, 27],
       [83, 42, 90, 94],
       [ 7, 74, 63, 28],
       [53, 95, 22, 37],
       [81, 33, 97, 11],
       [ 0, 23, 57, 27],
       [37, 24, 81, 11],
       [76, 59, 74, 90],
       [43, 82, 73, 42],
       [40, 87,  8, 21],
       [54, 73, 29,  6],
       [48, 89, 14, 62],
       [ 0, 45, 67, 94],
       [39, 98,  9, 18],
       [37, 61, 55, 84],
       [81, 75,  3, 43],
       [17, 76, 12, 95],
       [63, 98, 61, 87],
       [26, 21, 40, 11],
       [17, 47, 41, 36],
       [75, 80,  9, 63],
       [35,  4, 54, 63],
       [74, 53,  2, 81],
       [41, 70, 87, 87],
       [92, 11, 57, 26],
       [15, 16, 39, 47],
       [47, 72, 76, 44],
       [64, 51, 25, 97],
       [ 5, 64, 83, 93],
       [ 5, 88, 57, 72],
       [24, 23, 75,  7],
       [49,  4, 17, 15],
       [43,  0, 69, 95],
       [23, 88, 38, 61],
       [32, 62, 79, 13],
       [69, 91, 57, 42],
       [96, 76, 47, 10],
       [69,  9, 77, 21],
       [92, 14, 66, 47],
       [ 4, 12, 30, 93],
       [91, 16,  1, 77],
       [31, 15, 23,  7],
       [ 4, 58, 27, 52],
       [65, 26, 20, 62],
       [50, 48, 42, 27],
       [81, 20, 92, 93],
       [22, 30,  0, 83],
       [41, 23, 95, 17],
       [34, 89, 37, 54],
       [77, 21, 89, 31],
       [21, 36, 41, 75],
       [50, 46, 36, 59],
       [71, 58, 60,  0],
       [21, 72, 82, 39],
       [ 5, 94, 10,  5],
       [14, 93, 18, 29],
       [46, 72, 31, 10],
       [21, 30, 78, 52],
       [52, 78, 42, 30],
       [97, 74, 40, 81],
       [20, 47, 40, 30],
       [ 0, 25, 83, 73],
       [42, 94, 96,  3],
       [94, 95, 39, 48],
       [59,  4, 97,  1],
       [81, 76, 73, 17],
       [84, 11, 79, 13],
       [94, 48, 21, 98],
       [ 2, 76, 39, 90],
       [78, 15, 16, 58],
       [84, 44, 63, 63],
       [29, 25, 44, 31],
       [68, 11, 15, 32],
       [40, 21, 71, 70],
       [ 1, 53, 17, 87],
       [80, 49, 93, 16],
       [13, 37, 53, 80],
       [70, 15, 39, 94],
       [12, 18, 16,  1],
       [37, 79, 61, 57],
       [ 5, 69, 40, 46],
       [41,  8, 85, 16],
       [53, 94, 71, 46],
       [50, 40, 59, 67],
       [94, 44, 90,  6],
       [52, 64, 64, 77]])

In [5]:
dataframe = pd.DataFrame(data=datos, columns=['c1','c2','c3','etiqueta'])
dataframe

    c1  c2  c3  etiqueta
0   82  13  42        78
1   45  96  98        95
2   90  35  75        80
3   70   4   2        82
4   34  22  53        99
5   26  61  98        23
6   90  67  85        40
7   90  43  39        13
8   88  97   1        58
9   73  87  57        39
10  95  69  32         1
11  52  24   3         6
12   2  34  67        47
13  73  53   5        67
14   3  12  94        27
15  83  42  90        94
16   7  74  63        28
17  53  95  22        37
18  81  33  97        11
19   0  23  57        27
20  37  24  81        11
21  76  59  74        90
22  43  82  73        42
23  40  87   8        21
24  54  73  29         6
25  48  89  14        62
26   0  45  67        94
27  39  98   9        18
28  37  61  55        84
29  81  75   3        43
..  ..  ..  ..       ...
70  46  72  31        10
71  21  30  78        52
72  52  78  42        30
73  97  74  40        81
74  20  47  40        30
75   0  25  83        73
76  42  94  96         3
77  94  95  39        48
78  59   4  97         1
79  81  76  73        17
80  84  11  79        13
81  94  48  21        98
82   2  76  39        90
83  78  15  16        58
84  84  44  63        63
85  29  25  44        31
86  68  11  15        32
87  40  21  71        70
88   1  53  17        87
89  80  49  93        16
90  13  37  53        80
91  70  15  39        94
92  12  18  16         1
93  37  79  61        57
94   5  69  40        46
95  41   8  85        16
96  53  94  71        46
97  50  40  59        67
98  94  44  90         6
99  52  64  64        77

[100 rows x 4 columns]

In [7]:
X = dataframe[['c1','c2','c3']]
X

    c1  c2  c3
0   82  13  42
1   45  96  98
2   90  35  75
3   70   4   2
4   34  22  53
5   26  61  98
6   90  67  85
7   90  43  39
8   88  97   1
9   73  87  57
10  95  69  32
11  52  24   3
12   2  34  67
13  73  53   5
14   3  12  94
15  83  42  90
16   7  74  63
17  53  95  22
18  81  33  97
19   0  23  57
20  37  24  81
21  76  59  74
22  43  82  73
23  40  87   8
24  54  73  29
25  48  89  14
26   0  45  67
27  39  98   9
28  37  61  55
29  81  75   3
..  ..  ..  ..
70  46  72  31
71  21  30  78
72  52  78  42
73  97  74  40
74  20  47  40
75   0  25  83
76  42  94  96
77  94  95  39
78  59   4  97
79  81  76  73
80  84  11  79
81  94  48  21
82   2  76  39
83  78  15  16
84  84  44  63
85  29  25  44
86  68  11  15
87  40  21  71
88   1  53  17
89  80  49  93
90  13  37  53
91  70  15  39
92  12  18  16
93  37  79  61
94   5  69  40
95  41   8  85
96  53  94  71
97  50  40  59
98  94  44  90
99  52  64  64

[100 rows x 3 columns]

In [8]:
y= dataframe['etiqueta']
y

0     78
1     95
2     80
3     82
4     99
5     23
6     40
7     13
8     58
9     39
10     1
11     6
12    47
13    67
14    27
15    94
16    28
17    37
18    11
19    27
20    11
21    90
22    42
23    21
24     6
25    62
26    94
27    18
28    84
29    43
      ..
70    10
71    52
72    30
73    81
74    30
75    73
76     3
77    48
78     1
79    17
80    13
81    98
82    90
83    58
84    63
85    31
86    32
87    70
88    87
89    16
90    80
91    94
92     1
93    57
94    46
95    16
96    46
97    67
98     6
99    77
Name: etiqueta, Length: 100, dtype: int32

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [12]:
X_train.shape

(70, 3)

In [13]:
X_test.shape

(30, 3)

In [14]:
y_train.shape

(70,)

In [15]:
y_test.shape

(30,)